---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: search_engine
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: rabbitmq
  template:
    metadata:
      name: rabbitmq-pod
      labels:
        app: search_engine
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq