version: '3.3'
services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    volumes:
      - crawler_db:/data/db
    networks:
      back_net:
        aliases:
          - ui_db

  rabbitmq:
    image: rabbitmq:${RABBIT_VERSION}
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      back_net:

  engine:
    image: ${USER_NAME}/crawler-engine:${CRAWLER_ENGINE_VERSION}
    restart: on-failure
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO=mongodb
      - RMQ_HOST=rabbitmq
      - RMQ_USERNAME=rabbitmq
      - RMQ_PASSWORD=rabbitmq   
    networks:
      - back_net
      - front_net
  ui:
    image: ${USER_NAME}/crawler-ui:${CRAWLER_UI_VERSION}
    depends_on:
      - mongodb
    environment:
      - MONGO=mongodb
    ports:
      - "8000:8000"
    networks:
      - back_net
      - front_net

volumes:
  crawler_db:

networks:
  back_net:
  front_net: